blogapp/blog/urls.py
from django.urls import path
from .views import BlogView

app_name = 'blog'
urlpatterns = [
    path('', BlogView.as_view() , name = 'blog_list'),
    path('create/', BlogView.as_view() , name='blog_create'),
    path('<int:id>/<str:title>/', BlogView.as_view() , name='blog_detail'),
]
    

blogapp/blogapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog.views import BlogView


urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(
        template_name='blog/registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(
        next_page='login'), name='logout'),
    path('accounts/signup/', BlogView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogapp/blog/models.py
import os
from typing import Any
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.deconstruct import deconstructible

import datetime

# Create your models here.
@deconstructible
class UploadToPath(object):
    def __init__(self, path):
        self.sub_path = path
        
    
    def __call__(self, instance, filename):
        return os.path.join(self.sub_path, filename)

class Blog(models.Model):
    title = models.CharField(max_length=200)
    thumbnail = models.ImageField(upload_to=UploadToPath('blog/images/'))
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    modified_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return self.title
    
    

  

blogapp/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'thumbnail', 'content']
        
        
class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'input-class'})
    )
    
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'input-class'})
    )
    

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

blogapp/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator 
from django.contrib.auth import login, authenticate
from django.views.generic import View
from .models import Blog
from .forms import BlogForm, SignUpForm

class BlogView(View):
    def get(self, request, *args, **kwargs):
        if 'id' in kwargs and 'title' in kwargs:
            return self.blog_detail(request, kwargs['id'])
        else:
            return self.blog_list(request)


    def post(self, request, *args, **kwargs):
        if request.path == '/accounts/signup/':
            return self.signup(request)
        return self.blog_create(request)

    def blog_list(self, request):
        blogs = Blog.objects.all()
        return render(request, "blog/blog_list.html", {"blogs": blogs})


    @method_decorator(login_required)
    def blog_create(self, request):
        if request.method == "POST":
            form = BlogForm(request.POST, request.FILES)
            if form.is_valid():
                blog = form.save(commit=False)
                blog.author = request.user
                blog.save()
                return redirect("blog:blog_list")
        else:
            form = BlogForm()
        return render(request, 'blog/blog_create.html', {"form": form})


    def signup(self, request):
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                user.email = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                user.set_password(raw_password)
                user.save()
                user = authenticate(username=user.username, password=raw_password)
                login(request, user)
                return redirect('blog:blog_list')
        else:
            form = SignUpForm()
        return render(request, 'blog/registration/signup.html', {'form': form})
    

    def blog_detail(self, request, id):
        blog = Blog.objects.get(id=id)
        return render(request, 'blog/blog_detail.html', {'blog': blog})

blogapp/blog/templates/blog/blog_create.html
{% load static %}
{% load form_tags %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'blog/css/output.css' %}" />
    <title>Create Blog</title>
  </head>
  <body class="flex flex-col justify-center items-center w-full bg-teal-800 font-serif">
    <div class="flex flex-col justify-center items-center bg-teal-950 my-8 p-8 rounded-xl shadow-lg shadow-black w-1/2">
      <h1 class="text-[2rem] font-semibold mb-2 text-white">Create Blog Post</h1>
      <form method="post" enctype="multipart/form-data" action="{% url 'blog:blog_create' %}" class="space-y-2 w-full">
        {% csrf_token %}

        <label for="id_title" class="flex font-serif text-[20px] font-medium w-full text-white">Title</label>
        {{ form.title|add_attributes:'class:flex w-full p-2 border border-gray-300 rounded-md border-none outline-none, placeholder:Enter the title' }}

        <label for="id_content" class="flex font-serif text-[20px] font-medium w-full text-white">Content</label>
        {{ form.content|add_attributes:'class:flex w-full p-2 border border-gray-300 rounded-md border-none outline-none, placeholder:Enter the content' }}

        <label for="id_thumbnail" class="flex font-serif text-[20px] font-medium w-full text-white">Thumbnail</label>
        {{ form.thumbnail|add_attributes:'class:flex w-full border border-gray-300 bg-gray-100 rounded-md border-none outline-none' }}

        <button type="submit" class="w-full bg-teal-800 text-white shadow-lg shadow-black font-bold p-2 rounded-md hover:bg-teal-700 hover:shadow-lg hover:shadow-teal-500">Create</button>
      </form>
      <a href="{% url 'blog:blog_list' %}" class="block mt-4 text-teal-500 hover:text-teal-300">Back to Blog List</a>
    </div>
  </body>
</html>

blogapp/blog/templates/blog/blog_detail.html
{% extends 'blog/layout.html' %}

{% block content %}
    <div class="flex flex-col w-11/12 min-h-[82.75vh] p-4 items-center  bg-teal-950">
        {% if blog.thumbnail %}
        <img class=" h-[200px] w-[250px] rounded-xl flex items-center object-cover shadow-md shadow-black" src="{{ blog.thumbnail.url }}" alt="{{ blog.title }}" />
        {% else %}
            <p class="font-mono text-white">No image available</p>
        {% endif %}
        <div class="bg-white w-full rounded-2xl shadow-black shadow-lg mt-3 p-8">
            <h1 class="text-center font-bold text-2xl">{{ blog.title }}</h1>
            <p><span class="font-bold">Author: </span>{{ blog.author }}</p>
            <p><span class="font-bold">Created: </span>{{ blog.created_date }}</p>
            <p class="bg-teal-600 mt-2 pt-[2px] rounded-full"></p>
            <p class="mt-2 text-wrap">{{ blog.content }}</p>
        </div>
      <a href="{% url 'blog:blog_list' %}" class="block mt-4 text-teal-500 hover:text-teal-300 font-bold">Back to Blog List</a>
    </div>
{% endblock %}

blogapp/blog/templates/blog/blog_list.html
{% extends 'blog/layout.html' %}

{% block title %}
  Blog List
{% endblock %}

{% block content %}
  <div class="flex flex-col justify-evenly items-center h-[55vh] text-white">
    <h1 class="text-[2.5rem] font-serif font-bold text-center w-5/6">Your Daily Dose of Inspiration and Insight</h1>
    <p class="font-serif italic -mt-8">~ Unleash your creativity, one word at a time ~</p>
    <div class="flex flex-row space-x-4">
      <form action="{% if user.is_authenticated %}
          {% url 'blog:blog_create' %}
        {% else %}
          {% url 'login' %}?next={% url 'blog:blog_create' %}
        {% endif %}"
        method="post">
        {% csrf_token %}
        <button class="p-3 bg-teal-950 text-[1rem] rounded-lg shadow-md shadow-teal-600 hover:shadow-lg hover:shadow-teal-500 hover:opacity-85 font-semibold">Create Blogs</button>
      </form>
      {% if user.is_authenticated %}
        <button class="p-3 bg-teal-950 text-[1rem] rounded-lg shadow-md shadow-teal-600 hover:shadow-lg hover:shadow-teal-500 hover:opacity-85 font-semibold">Manage Blogs</button>
      {% endif %}
    </div>
  </div>

  <div class="flex flex-col justify-center items-center w-11/12 rounded-t-2xl bg-teal-950 shadow-lg shadow-black">
    <h1 class="font-serif font-bold text-[2.5rem] text-white pt-3">Blog List</h1>

    <form class="w-3/5 my-2">
      <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
          </svg>
        </div>
        <input type="search" class="block w-full p-3 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 placeholder-gray-400 text-[1rem] focus:outline-none" placeholder="Search Blogs" required />
        <button type="submit" class="text-white absolute end-[4.5px] bottom-[4.5px] bg-teal-800 focus:outline-none font-medium rounded-lg text-sm px-4 py-2 hover:bg-teal-700">Search</button>
      </div>
    </form>

    <div class="flex flex-row justify-evenly items-center flex-wrap gap-x-4 gap-y-10 p-4 pb-8 w-full">
      {% for blog in blogs %}
        <a href="{% url 'blog:blog_detail' blog.id blog.title %}">
          <div class="w-[300px] max-h-[400px] h-[390px] bg-white rounded-lg shadow-teal-600 shadow-lg hover:shadow-xl hover:shadow-teal-500">
            {% if blog.thumbnail %}
                <img class="rounded-t-lg w-full h-[175px] object-cover" src="{{ blog.thumbnail.url }}" alt="{{ blog.title }}" />
            {% else %}
                <p class="rounded-t-lg w-full h-[175px] object-cover bg-gray-400 text-center flex flex-col justify-center font-medium">No image available</p>
            {% endif %}
            <div class="p-5 flex flex-col justify-around items-start">
              <h5 class="text-2xl font-bold tracking-tight text-gray-900 font-serif">{{ blog.title }}</h5>
              <p class="text-sm text-gray-600">
                Author: <span class="font-semibold">{{ blog.author.username }}</span>
              </p>
              <p class="text-sm text-gray-600">
                Created At: <span class="font-semibold">{{ blog.created_at }}</span>
              </p>
              <p class="mt-1 w-full h-[1px] bg-gray-600 mb-2"></p>
              <p class="mb-3 font-normal text-gray-700 text-wrap ">{{ blog.content|truncatechars:70 }}</p>
              <div class=" inline-flex items-center justify-center px-3 py-2 text-sm font-medium text-center text-white bg-teal-700 rounded-lg hover:bg-teal-800 focus:outline-none focus:teal-300">
                Read more<svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9" />
                </svg>
              </div>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

blogapp/blog/templates/blog/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Blog App
      {% endblock %}
    </title>
    <link href="{% static 'blog/css/output.css' %}" rel="stylesheet" />
  </head>
  <body class="flex flex-col bg-gradient-to-b from-teal-600 to-teal-800 bg-no-repeat bg-fixed h-screen justify-between">
    <nav class="bg-red-950 shadow-lg shadow-teal-950 border-black border-b-[2px] border-opacity-30">
      <div class="w-full flex flex-wrap items-center justify-between p-4">
        <a href="{% url 'blog:blog_list' %}"><img src="{% static 'blog/images/logo.svg' %}" class="h-10" alt="Blog App Logo" /></a>
        <a href="{% url 'blog:blog_list' %}"><p class="text-white font-semibold text-[1.75rem] font-serif">Blog App</p></a>
        <div class="flex items-center space-x-3">
          <button type="button" class="flex text-sm bg-gray-800 rounded-full" id="user-menu-button">
            <span class="sr-only">Open user menu</span>
            <img class="w-8 h-8 rounded-full" src="{% static 'blog/images/user_icon.png' %}" alt="user photo" />
          </button>
          <div class="absolute top-7 right-1 mt-10 w-48 z-50 hidden text-base list-none divide-y rounded-lg shadow bg-teal-950 divide-teal-600" id="user-dropdown">
            {% if user.is_authenticated %}
              <div class="px-4 py-3">
                <span class="block text-sm text-white">{{ user.username }}</span>
                <span class="block text-sm truncate text-gray-400">{{ user.email }}</span>
              </div>
              <ul class="py-2">
                <li>
                  <a href="#" class="block px-4 py-2 text-sm hover:bg-teal-900 text-gray-200 hover:text-white">Account</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm hover:bg-teal-900 text-gray-200 hover:text-white">Manage Blogs</a>
                </li>
                <li>
                  <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="w-full text-left block px-4 py-2 text-sm hover:bg-teal-900 text-gray-200 hover:text-white">Logout</button>
                  </form>
                </li>
              </ul>
            {% else %}
              <ul class="py-2">
                <li>
                  <a href="{% url 'login' %}" class="block px-4 py-2 text-sm hover:bg-teal-900 text-gray-200 hover:text-white">Login</a>
                </li>
                <li>
                  <a href="{% url 'signup' %}" class="block px-4 py-2 text-sm hover:bg-teal-900 text-gray-200 hover:text-white">Sign up</a>
                </li>
              </ul>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>

    <div class="content w-full flex flex-col justify-center items-center">
      {% block content %}

      {% endblock %}
    </div>

    <footer class="flex justify-center items-center w-full">
      <div class="flex flex-row w-full justify-center items-center text-white bg-black bg-opacity-90 font-mono">
        <p>&copy; {{ year }} Blog App. All rights reserved.</p>
      </div>
    </footer>
  </body>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      var button = document.getElementById('user-menu-button')
      var dropdown = document.getElementById('user-dropdown')
    
      button.addEventListener('click', function (event) {
        dropdown.classList.toggle('hidden')
        event.stopPropagation()
      })
    
      document.addEventListener('click', function (event) {
        var isClickInsideDropdown = dropdown.contains(event.target)
        var isClickInsideButton = button.contains(event.target)
    
        if (!isClickInsideDropdown && !isClickInsideButton) {
          dropdown.classList.add('hidden')
        }
      })
    })
  </script>
</html>